Green_Stuff/Controllers/SalesController.cs
using Green_Stuff.Models;
using Green_Stuff.Models.ViewModels;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System.Data;
using System.Data.SqlClient;

namespace Green_Stuff.Controllers
{
    public class SalesController : Controller
    {
        private readonly string cadenaSQL;
        private readonly DbLabpwebContext _DBContext;
        public SalesController(IConfiguration config, DbLabpwebContext context)
        {
            cadenaSQL = config.GetConnectionString("cadenaSQL");
            _DBContext = context;
        }
        // GET: SalesController
        public ActionResult Index()
        {
            return View();
        }

        public IActionResult SalesSummary()
        {
            DateTime StartDate = DateTime.Now;
            StartDate = StartDate.AddDays(-5);
            List<SalesVM> list = (from sales in _DBContext.Sales
                                  where sales.CreationDate.Date >= StartDate.Date
                                  group sales by sales.CreationDate.Date into grupo
                                  select new SalesVM
                                  {
                                      fecha = grupo.Key.ToString("dd/MM/yyyy"),
                                      cantidad = grupo.Count()
                                  }).ToList();
            return StatusCode(StatusCodes.Status200OK, list);
        }

        public IActionResult SaleDetailSummary()
        {
            List<Sale_DetailVM> list = (from salesdetail in _DBContext.SaleDetails
                                        join warehouse in _DBContext.Warehouses
                                        on salesdetail.Iditem equals warehouse.IdItem
                                        group salesdetail by warehouse.Name into grouped
                                        select new Sale_DetailVM
                                        {
                                            producto = grouped.Key,
                                            cantidad = grouped.Sum(g => g.Quantity)
                                        }).OrderByDescending(vm => vm.cantidad).Take(4).ToList();

            return StatusCode(StatusCodes.Status200OK, list);
        }

        [HttpGet]
        public JsonResult ListaSales()
        {
            List<SalesAnalisysVM> list = new List<SalesAnalisysVM>();
            using (var connection = new SqlConnection(cadenaSQL))
            {
                connection.Open();
                var cmd = new SqlCommand("sp_list_Sales", connection);
                cmd.CommandType = CommandType.StoredProcedure;
                using (var reader = cmd.ExecuteReader())
                {
                    while (reader.Read())
                    {
                        list.Add(new SalesAnalisysVM
                        {
                            IdSale = Convert.ToInt32(reader["ID_Sale"]),
                            Iduser = 0,
                            Username = reader["Username"].ToString(),
                            Idcard = 0,
                            P_Card = reader["P_Card"].ToString(),
                            TotalAmmount = Convert.ToDecimal(reader["TotalAmmount"]),
                            Cdate = reader["CreationDate"].ToString(),
                            TotalQuantity = Convert.ToDecimal(reader["TotalQuantity"])
                        });
                    }
                }
            }
            return Json(new { data = list });
        }

        // GET: SalesController/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: SalesController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: SalesController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: SalesController/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: SalesController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: SalesController/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: SalesController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

Green_Stuff/Views/Shared/_Layout.cshtml
@{
    var userType = Context.Session.GetString("UserType");
    var userName = Context.Session.GetString("Username");
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Green_Stuff</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Green_Stuff.styles.css" asp-append-version="true" />
    @await RenderSectionAsync("Estilos", required: false)
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">
                    <img src="~/Resources/Images/Background/logo.png" width="100"/>
                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        @if (userType == "Administrador")
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Warehouse" asp-action="Index">Almacen</a>
                            </li>
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                    Filtros
                                </a>
                                <ul class="dropdown-menu">
                                    <li><a class="dropdown-item" asp-area="" asp-controller="Sizes" asp-action="Index">Tamaños</a></li>
                                    <li><a class="dropdown-item" asp-area="" asp-controller="ExpositionToSun" asp-action="Index">Exposición al sol</a></li>
                                    <li><a class="dropdown-item" asp-area="" asp-controller="WaterDemmand" asp-action="Index">Demanda de agua</a></li>
                                    <li><a class="dropdown-item" asp-area="" asp-controller="Category" asp-action="Index">Categorías</a></li>
                                </ul>
                            </li>
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                    Usuarios
                                </a>
                                <ul class="dropdown-menu">
                                    <li><a class="dropdown-item" asp-area="" asp-controller="User" asp-action="Index">Usuarios</a></li>
                                    <li><a class="dropdown-item" asp-area="" asp-controller="Addresses" asp-action="Index">Direcciones</a></li>
                                    <li><a class="dropdown-item" asp-area="" asp-controller="UserType" asp-action="Index">Catálogo</a></li>
                                    <li><a class="dropdown-item" asp-area="" asp-controller="PaymentCards" asp-action="Index">Tarjetas de pago</a></li>
                                </ul>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Advertisements" asp-action="Index">Anuncios</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Sales" asp-action="Index">Ventas</a>
                            </li>
                        }
                        else if (userType == "Cliente")
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Products" asp-action="Index">Productos</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Cart" asp-action="Index">Carrito</a>
                            </li>
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                    Mi Perfil
                                </a>
                                <ul class="dropdown-menu">
                                    <li><a class="dropdown-item" asp-area="" asp-controller="Account" asp-action="EditProfile">Editar Perfil</a></li>
                                    <li><a class="dropdown-item" asp-area="" asp-controller="Account" asp-action="PaymentCards">Mis Tarjetas de Pago</a></li>
                                </ul>
                            </li>
                        }else{

                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Products" asp-action="Index">Productos</a>
                            </li>
                        }
                        @if (!string.IsNullOrEmpty(userName))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Acceso" asp-action="Salir">Cerrar Sesión (@userName)</a>
                            </li>
                        }
                        else
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Acceso" asp-action="Login">Login</a>
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
            <h3>@userName</h3>
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - Green_Stuff - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script type="module" src="~/lib/Chartjs/chart.umd.min.js"></script>
    <!--<script type="module" src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/4.4.1/chart.min.js" integrity="sha512-L0Shl7nXXzIlBSUUPpxrokqq4ojqgZFQczTYlGjzONGTDAcLremjwaWv5A+EDLnxhQzY5xUZPWLOLqYRkY0Cbw==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>-->
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>